import { Line, LineDocument } from '@lines/models/schemas/line.schema';
import { Injectable } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { Model } from 'mongoose';

@Injectable()
export class LinesService {
  constructor(
    @InjectModel(Line.name)
    private readonly lineModel: Model<LineDocument>,
  ) {}

  async findAll(): Promise<Line[]> {
    return this.lineModel
      .find()
      .sort({
        _id: 1,
      })
      .exec();
  }

  async seed() {
    const lines: Line[] = [
      { name: '1' },
      { name: '2' },
      { name: '3' },
      { name: '4' },
      { name: '5' },
      { name: '6' },
      { name: '7' },
      { name: '8' },
      { name: '9 AMARILLO' },
      { name: '9 VERDE' },
      { name: '10' },
      { name: '11' },
      { name: '12' },
      { name: '13' },
      { name: '14 AZUL' },
      { name: '14 ROJO' },
      { name: '15' },
      { name: '16 AZUL' },
      { name: '16 ROJO' },
      { name: '17' },
      { name: '18' },
      { name: '19' },
      { name: '20' },
      { name: '21' },
      { name: '22 AMARILLO' },
      { name: '22 ROJO' },
      { name: '23' },
      { name: '24' },
      { name: '25' },
      { name: '26' },
      { name: '27 AZUL' },
      { name: '27 ROJO' },
      { name: '28 AMARILLO' },
      { name: '28 VERDE' },
      { name: '29' },
      { name: '30' },
      { name: '31' },
      { name: '32 ROJO' },
      { name: '32 VERDE' },
      { name: '33' },
      { name: '34' },
      { name: '35' },
      { name: '36' },
      { name: '37' },
      { name: '38' },
      { name: '39' },
      { name: '40' },
      { name: '41' },
      { name: '42' },
      { name: '43' },
      { name: '43 LAGUNA' },
      { name: '44 AZUL' },
      { name: '44 ROJO' },
      { name: '45' },
      { name: '46' },
      { name: '47' },
      { name: '48' },
      { name: '49' },
      { name: '50' },
      { name: '51' },
      { name: '52' },
      { name: '53' },
      { name: '54' },
      { name: '55' },
      { name: '56' },
      { name: '57' },
      { name: '58' },
      { name: '59' },
      { name: '60 ROJO' },
      { name: '60 VERDE' },
      { name: '61' },
      { name: '62 NARANJA' },
      { name: '62 VERDE' },
      { name: '63' },
      { name: '64 AMARILLO' },
      { name: '64 ROJO' },
      { name: '65' },
      { name: '66 AZUL' },
      { name: '66 ROJO' },
      { name: '67' },
      { name: '68' },
      { name: '69' },
      { name: '70' },
      { name: '71' },
      { name: '72' },
      { name: '73' },
      { name: '74' },
      { name: '75' },
      { name: '76' },
      { name: '77' },
      { name: '78' },
      { name: '79' },
      { name: '80' },
      { name: '81' },
      { name: '82' },
      { name: '83' },
      { name: '84' },
      { name: '85 FORTALEZA' },
      { name: '85' },
      { name: '86' },
      { name: '87' },
      { name: '88 AMARILLA' },
      { name: '88 AZUL' },
      { name: '89' },
      { name: '90' },
      { name: '92' },
      { name: '94' },
      { name: '96 AMARILLO' },
      { name: '96' },
      { name: '97' },
      { name: '98' },
      { name: '99' },
      { name: '100' },
      { name: '101 ANGOSTURA' },
      { name: '103' },
      { name: '104 C' },
      { name: '104 ROJO' },
      { name: '105 ROJO' },
      { name: '105 VERDE' },
      { name: '106' },
      { name: '107' },
      { name: '108' },
      { name: '109' },
      { name: '110' },
      { name: '111' },
      { name: '112' },
      { name: '113' },
      { name: '115' },
      { name: '116' },
      { name: '119 AZUL' },
      { name: '119 ROJO' },
      { name: '120' },
      { name: '121' },
      { name: '122' },
      { name: '123' },
      { name: '124' },
      { name: '125' },
      { name: '126' },
      { name: '127' },
      { name: '129' },
      { name: '130' },
      { name: '131 COTOCA' },
      { name: '132 MONTERO' },
      { name: '132' },
      { name: '133 EL TORNO' },
      { name: '133 LA GUARDIA' },
      { name: '135 VIRU VIRU' },
      { name: '136 INTERMUNICIPAL' },
      { name: '136 URBANO' },
      { name: '137 LAS BRECHAS' },
      { name: '140 AZUL' },
      { name: '140 ROJO' },
      { name: '141' },
      { name: '151' },
    ];
    return this.lineModel.insertMany(lines);
  }
}
